### ISSUE TITLE
Incorrect shortcut key for algebraic evaluation.

### ISSUE THREAD

**Issue by sykloid** [SueDNymme/emacs-calc-qref#3]
You've listed `a l` as the key to evaluate an algebraic expression by temporarily setting a variable. However, this key doesn't appear to be bound in calc.

The `s l` key however is bound, to `calc-let`, which does exactly you want from `a l`. Further, `s l` isn't listed in the store/recall section.

Did you perhaps mean `s l` instead of `a l`?

**Comment by SueDNymme** [comment]
I do believe you are right!  Thank you very much for your correction.

**Comment by SueDNymme** [comment]
Fixed in v1.06.
